[package]
name = "screen-qr-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
screenshots = "0.4.3"
quircs = "0.10.0"
show-image = {version= "0.12.3", features= ["image"]}
